// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvBnY9Rr1IKo2knuNVTAgELyjbV0ra7EQ',
    appId: '1:1090721096384:web:aa4dcc4850b353107b4325',
    messagingSenderId: '1090721096384',
    projectId: 'my-chat-9f29f',
    authDomain: 'my-chat-9f29f.firebaseapp.com',
    storageBucket: 'my-chat-9f29f.appspot.com',
    measurementId: 'G-JYQYRRH9YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcvtXuE5mGdhZeEFM5C_mWY10BjdXW6Kc',
    appId: '1:1090721096384:android:de0f071b544055e37b4325',
    messagingSenderId: '1090721096384',
    projectId: 'my-chat-9f29f',
    storageBucket: 'my-chat-9f29f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVav668evGPxkunnyQ5Zqa22uCOiLMaRY',
    appId: '1:1090721096384:ios:736a66535689408b7b4325',
    messagingSenderId: '1090721096384',
    projectId: 'my-chat-9f29f',
    storageBucket: 'my-chat-9f29f.appspot.com',
    iosBundleId: 'com.example.myChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVav668evGPxkunnyQ5Zqa22uCOiLMaRY',
    appId: '1:1090721096384:ios:bc59d8c4bce814147b4325',
    messagingSenderId: '1090721096384',
    projectId: 'my-chat-9f29f',
    storageBucket: 'my-chat-9f29f.appspot.com',
    iosBundleId: 'com.example.myChat.RunnerTests',
  );
}
